create table etl_batch (
    batch_id        number generated by default as identity primary key,
    batch_name      varchar2(100) not null,
    status          varchar2(20) not null,
    started_at      timestamp default systimestamp not null,
    finished_at     timestamp,
    rows_read       number default 0 not null,
    rows_inserted   number default 0 not null,
    rows_updated    number default 0 not null,
    rows_rejected   number default 0 not null,
    created_by      varchar2(128) default user not null,
    constraint ck_etl_batch_status
        check (status in ('RUNNING','SUCCESS','FAILED','PARTIAL'))
);

create table etl_job (
    job_id          number generated by default as identity primary key,
    job_name        varchar2(100) not null,
    description     varchar2(500),
    enabled_flag    char(1) default 'Y' not null,
    constraint uq_etl_job_name unique (job_name),
    constraint ck_etl_job_enabled check (enabled_flag in ('Y','N'))
);

create table etl_job_run (
    job_run_id      number generated by default as identity primary key,
    batch_id        number not null,
    job_id          number not null,
    status          varchar2(20) not null,
    started_at      timestamp default systimestamp not null,
    finished_at     timestamp,
    rows_read       number default 0 not null,
    rows_inserted   number default 0 not null,
    rows_updated    number default 0 not null,
    rows_rejected   number default 0 not null,
    constraint fk_etl_job_run_batch foreign key (batch_id)
        references etl_batch(batch_id),
    constraint fk_etl_job_run_job foreign key (job_id)
        references etl_job(job_id),
    constraint ck_etl_job_run_status
        check (status in ('RUNNING','SUCCESS','FAILED','PARTIAL'))
);

create table etl_error_log (
    error_id        number generated by default as identity primary key,
    batch_id        number,
    job_run_id      number,
    module          varchar2(200),
    error_code      number,
    error_message   varchar2(4000),
    backtrace       varchar2(4000),
    created_at      timestamp default systimestamp not null
);

create table etl_rejected_row (
    reject_id       number generated by default as identity primary key,
    batch_id        number,
    job_run_id      number,
    source_key      varchar2(500),
    reject_reason   varchar2(2000) not null,
    source_payload  clob,
    created_at      timestamp default systimestamp not null
);
